project:
  type: website
  output-dir: docs
 
website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: trabajo.qmd
        text: Trabajo_Ecuador
      - href: clasificacion_binaria.qmd
        text: Clasificación Binaria
      - href: regresion_hogares.qmd
        text: Regresión Hogares
 
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
    df-max-print: 10000